package adminapi

import (
	"crypto/rand"
	"encoding/csv"
	"fmt"
	"math/big"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/talkincode/toughradius/v9/internal/domain"
	"github.com/talkincode/toughradius/v9/internal/webserver"
	"github.com/talkincode/toughradius/v9/pkg/common"
	"go.uber.org/zap"
)

// ListVoucherBatches retrieves the voucher batch list
// @Summary get the voucher batch list
// @Tags Voucher
// @Param page query int false "Page number"
// @Param perPage query int false "Items per page"
// @Param sort query string false "Sort field"
// @Param order query string false "Sort direction"
// @Success 200 {object} ListResponse
// @Router /api/v1/voucher-batches [get]
func ListVoucherBatches(c echo.Context) error {
	db := GetDB(c)

	page, _ := strconv.Atoi(c.QueryParam("page"))
	perPage, _ := strconv.Atoi(c.QueryParam("perPage"))
	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 100 {
		perPage = 10
	}

	sortField := c.QueryParam("sort")
	order := c.QueryParam("order")
	if sortField == "" {
		sortField = "id"
	}
	if order != "ASC" && order != "DESC" {
		order = "DESC"
	}

	var total int64
	var batches []domain.VoucherBatch

	// Permission check
	currentUser, err := resolveOperatorFromContext(c)
	if err != nil {
		return fail(c, http.StatusUnauthorized, "UNAUTHORIZED", "Authentication failed", err.Error())
	}

	query := db.Model(&domain.VoucherBatch{})

	// Filter by agent: Agents can only see their own batches
	if currentUser.Level == "agent" {
		query = query.Where("agent_id = ? AND is_deleted = ?", currentUser.ID, false)
	} else {
		// Admin: show deleted batches if requested, or filter out by default
		if c.QueryParam("is_deleted") == "true" {
			query = query.Where("is_deleted = ?", true)
		} else if c.QueryParam("is_deleted") == "false" {
			query = query.Where("is_deleted = ?", false)
		}
	}

	// Filter by name
	if name := strings.TrimSpace(c.QueryParam("name")); name != "" {
		query = query.Where("name LIKE ?", "%"+name+"%")
	}

	query.Count(&total)

	offset := (page - 1) * perPage
	query.Order(sortField + " " + order).Limit(perPage).Offset(offset).Find(&batches)

	return paged(c, batches, total, page, perPage)
}

// ListVouchers retrieves the voucher list
// @Summary get the voucher list
// @Tags Voucher
// @Param page query int false "Page number"
// @Param perPage query int false "Items per page"
// @Param batch_id query int false "Batch ID"
// @Param status query string false "Status"
// @Success 200 {object} ListResponse
// @Router /api/v1/vouchers [get]
func ListVouchers(c echo.Context) error {
	db := GetDB(c)

	page, _ := strconv.Atoi(c.QueryParam("page"))
	perPage, _ := strconv.Atoi(c.QueryParam("perPage"))
	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 100 {
		perPage = 10
	}

	var total int64
	var vouchers []domain.Voucher

	query := db.Model(&domain.Voucher{})

	if batchID := c.QueryParam("batch_id"); batchID != "" {
		query = query.Where("batch_id = ?", batchID)
	}

	if status := c.QueryParam("status"); status != "" {
		query = query.Where("status = ?", status)
	}

	if code := c.QueryParam("code"); code != "" {
		query = query.Where("code = ?", code)
	}

	query.Count(&total)

	offset := (page - 1) * perPage
	query.Order("id DESC").Limit(perPage).Offset(offset).Find(&vouchers)

	return paged(c, vouchers, total, page, perPage)
}

// VoucherBatchRequest
type VoucherBatchRequest struct {
	Name       string `json:"name" validate:"required"`
	ProductID  string `json:"product_id" validate:"required"`
	Count      int    `json:"count" validate:"required,min=1,max=10000"`
	Prefix     string `json:"prefix" validate:"omitempty,max=10"`
	Length     int    `json:"length" validate:"min=6,max=20"` // Length of random part
	Type       string `json:"type"`                           // number, alpha, mixed
	Remark     string `json:"remark"`
	AgentID    string `json:"agent_id" validate:"omitempty"` // Optional, if generated by agent
	ExpireTime string `json:"expire_time"`                   // ISO8601 string
}

func generateVoucherCode(length int, charType string) string {
	const (
		numbers = "0123456789"
		alpha   = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
		mixed   = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	)

	var charset string
	switch charType {
	case "number":
		charset = numbers
	case "alpha":
		charset = alpha
	default:
		charset = mixed
	}

	// Remove confusing characters
	charset = strings.ReplaceAll(charset, "0", "")
	charset = strings.ReplaceAll(charset, "O", "")
	charset = strings.ReplaceAll(charset, "1", "")
	charset = strings.ReplaceAll(charset, "I", "")
	charset = strings.ReplaceAll(charset, "l", "")

	result := make([]byte, length)
	maxParam := big.NewInt(int64(len(charset)))

	for i := 0; i < length; i++ {
		n, _ := rand.Int(rand.Reader, maxParam)
		result[i] = charset[n.Int64()]
	}

	return string(result)
}

// CreateVoucherBatch generates vouchers
// @Summary create voucher batch
// @Tags Voucher
// @Param batch body VoucherBatchRequest true "Batch info"
// @Success 201 {object} domain.VoucherBatch
// @Router /api/v1/voucher-batches [post]
func CreateVoucherBatch(c echo.Context) error {
	var req VoucherBatchRequest
	if err := c.Bind(&req); err != nil {
		return fail(c, http.StatusBadRequest, "INVALID_REQUEST", "Unable to parse request", err.Error())
	}

	if err := c.Validate(&req); err != nil {
		return err
	}

	if req.Length == 0 {
		req.Length = 10
	}

	productID, _ := strconv.ParseInt(req.ProductID, 10, 64)

	// Validate Product
	var product domain.Product
	if err := GetDB(c).First(&product, productID).Error; err != nil {
		return fail(c, http.StatusBadRequest, "INVALID_PRODUCT", "Product not found", nil)
	}

	// Securely get current user to enforce AgentID
	currentUser, err := resolveOperatorFromContext(c)
	if err != nil {
		return fail(c, http.StatusUnauthorized, "UNAUTHORIZED", "Authentication failed", err.Error())
	}

	// If user is an agent, force the AgentID to be their own ID
	if currentUser.Level == "agent" {
		req.AgentID = fmt.Sprintf("%d", currentUser.ID)
	}

	// Start Transaction
	tx := GetDB(c).Begin()

	agentID, _ := strconv.ParseInt(req.AgentID, 10, 64)
	var finalCost float64

	// Agent Wallet Logic
	if agentID > 0 {
		finalCost = product.CostPrice * float64(req.Count)
		// Fallback to retail price if cost price is not set
		if finalCost <= 0 && product.Price > 0 {
			finalCost = product.Price * float64(req.Count)
		}

		var wallet domain.AgentWallet
		if err := tx.Set("gorm:query_option", "FOR UPDATE").FirstOrCreate(&wallet, domain.AgentWallet{AgentID: agentID}).Error; err != nil {
			tx.Rollback()
			return fail(c, http.StatusInternalServerError, "WALLET_ERROR", "Failed to lock wallet", err.Error())
		}

		if wallet.Balance < finalCost {
			tx.Rollback()
			return fail(c, http.StatusPaymentRequired, "INSUFFICIENT_FUNDS", "Insufficient wallet balance", nil)
		}

		// Deduct Balance
		newBalance := wallet.Balance - finalCost
		if err := tx.Model(&domain.AgentWallet{}).Where("agent_id = ?", agentID).Updates(map[string]interface{}{"balance": newBalance, "updated_at": time.Now()}).Error; err != nil {
			tx.Rollback()
			return fail(c, http.StatusInternalServerError, "WALLET_UPDATE_FAILED", "Failed to update balance", err.Error())
		}

		// Log Transaction
		log := domain.WalletLog{
			AgentID:     agentID,
			Type:        "purchase",
			Amount:      -finalCost,
			Balance:     newBalance,
			ReferenceID: "batch-" + common.UUID(),
			Remark:      fmt.Sprintf("generated %d vouchers from %s", req.Count, product.Name),
			CreatedAt:   time.Now(),
		}

		// We'll update ReferenceID with BatchID after batch creation, or just use UUID
		if err := tx.Create(&log).Error; err != nil {
			tx.Rollback()
			return fail(c, http.StatusInternalServerError, "LOG_FAILED", "Failed to create transaction log", err.Error())
		}
	}

	batch := domain.VoucherBatch{
		Name:      req.Name,
		ProductID: productID,
		AgentID:   agentID, // Link to Agent
		Count:     req.Count,
		Prefix:    req.Prefix,
		Remark:    req.Remark,
		CreatedAt: time.Now(),
	}

	if req.ExpireTime != "" {
		if t, err := time.Parse(time.RFC3339, req.ExpireTime); err == nil {
			batch.ExpireTime = &t
		}
	}

	if err := tx.Create(&batch).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "CREATE_FAILED", "Failed to create batch record", err.Error())
	}

	// Generate Vouchers
	vouchers := make([]domain.Voucher, 0, req.Count)

	var expireTime time.Time
	if batch.ExpireTime != nil {
		expireTime = *batch.ExpireTime
	}

	for i := 0; i < req.Count; i++ {
		code := req.Prefix + generateVoucherCode(req.Length, req.Type)

		vouchers = append(vouchers, domain.Voucher{
			BatchID:    batch.ID,
			Code:       code,
			Status:     "unused",
			Price:      product.Price,
			AgentID:    agentID, // Link to Agent
			ExpireTime: expireTime,
			CreatedAt:  time.Now(),
			UpdatedAt:  time.Now(),
		})
	}

	// Batch Insert
	if err := tx.CreateInBatches(vouchers, 100).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "GENERATE_FAILED", "Failed to insert vouchers", err.Error())
	}

	tx.Commit()

	return ok(c, batch)
}

// VoucherRedeemRequest
type VoucherRedeemRequest struct {
	Code string `json:"code" validate:"required"`
}

// RedeemVoucher activates a voucher and creates a Radius user
// @Summary redeem a voucher
// @Tags Voucher
// @Param redeem body VoucherRedeemRequest true "Redeem info"
// @Success 200 {object} domain.RadiusUser
// @Router /api/v1/vouchers/redeem [post]
func RedeemVoucher(c echo.Context) error {
	var req VoucherRedeemRequest
	if err := c.Bind(&req); err != nil {
		return fail(c, http.StatusBadRequest, "INVALID_REQUEST", "Unable to parse request", err.Error())
	}

	if err := c.Validate(&req); err != nil {
		return err
	}

	tx := GetDB(c).Begin()

	// 1. Find Voucher
	var voucher domain.Voucher
	if err := tx.Set("gorm:query_option", "FOR UPDATE").Where("code = ?", req.Code).First(&voucher).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusNotFound, "INVALID_CODE", "Voucher code not found", nil)
	}

	if voucher.Status != "unused" {
		tx.Rollback()
		return fail(c, http.StatusConflict, "VOUCHER_USED", "Voucher already used or expired", nil)
	}

	if !voucher.ExpireTime.IsZero() && voucher.ExpireTime.Before(time.Now()) {
		tx.Rollback()
		return fail(c, http.StatusConflict, "VOUCHER_EXPIRED", "Voucher has expired", nil)
	}

	// 2. Get Product and Profile
	var product domain.Product
	var batch domain.VoucherBatch
	if err := tx.First(&batch, voucher.BatchID).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "BATCH_ERROR", "Voucher batch not found", err.Error())
	}

	if err := tx.First(&product, batch.ProductID).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "PRODUCT_ERROR", "Associated product not found", err.Error())
	}

	var profile domain.RadiusProfile
	if err := tx.First(&profile, product.RadiusProfileID).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "PROFILE_ERROR", "Associated profile not found", err.Error())
	}

	// 3. Create Radius User
	// User/Pass is the voucher code
	now := time.Now()
	expireTime := now.Add(time.Duration(product.ValiditySeconds) * time.Second)

	user := domain.RadiusUser{
		Username:   voucher.Code,
		Password:   voucher.Code,
		ProfileId:  profile.ID,
		Status:     "enabled",
		ExpireTime: expireTime,
		CreatedAt:  now,
		UpdatedAt:  now,
		// Inherit limits from Profile if needed, or rely on ProfileID linkage in Radius Server
		// Usually distinct limits are copied to user to allow overrides,
		// but if Radius Server checks Profile, we just need the link.
		// Checking RadiusUser struct... it has UpRate/DownRate.
		// Let's copy them from Profile to be safe/consistent.
		UpRate:   profile.UpRate,
		DownRate: profile.DownRate,
		AddrPool: profile.AddrPool,
	}

	if err := tx.Create(&user).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "USER_CREATE_FAILED", "Failed to create user", err.Error())
	}

	// 4. Update Voucher Status
	voucher.Status = "used"
	voucher.RadiusUsername = user.Username
	voucher.ActivatedAt = now

	if err := tx.Save(&voucher).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "VOUCHER_UPDATE_FAILED", "Failed to update voucher status", err.Error())
	}

	tx.Commit()

	return ok(c, user)
}

// BulkActivateVouchers activates all vouchers in a batch
func BulkActivateVouchers(c echo.Context) error {
	id := c.Param("id")
	if err := GetDB(c).Model(&domain.Voucher{}).Where("batch_id = ? AND status = ?", id, "unused").Update("status", "active").Error; err != nil {
		return fail(c, http.StatusInternalServerError, "UPDATE_FAILED", "Failed to activate vouchers", err.Error())
	}
	return ok(c, nil)
}

// BulkDeactivateVouchers deactivates all active vouchers in a batch
func BulkDeactivateVouchers(c echo.Context) error {
	id := c.Param("id")

	// Find all active vouchers in this batch to get their codes (usernames)
	var vouchers []domain.Voucher
	if err := GetDB(c).Where("batch_id = ? AND status = ?", id, "active").Find(&vouchers).Error; err != nil {
		return fail(c, http.StatusInternalServerError, "QUERY_FAILED", "Failed to query vouchers", err.Error())
	}

	// Disconnect online sessions for these vouchers
	for _, v := range vouchers {
		var session domain.RadiusOnline
		// Check if user is online
		if err := GetDB(c).Where("username = ?", v.Code).First(&session).Error; err == nil {
			// User is online, disconnect them
			if err := DisconnectSession(c, session); err != nil {
				// Log error but continue with other vouchers
				zap.L().Error("Failed to disconnect voucher user",
					zap.String("username", v.Code),
					zap.Error(err))
			}
		}
	}

	if err := GetDB(c).Model(&domain.Voucher{}).Where("batch_id = ? AND status = ?", id, "active").Update("status", "unused").Error; err != nil {
		return fail(c, http.StatusInternalServerError, "UPDATE_FAILED", "Failed to deactivate vouchers", err.Error())
	}
	return ok(c, nil)
}

// DeleteVoucherBatch soft deletes a batch and its vouchers
func DeleteVoucherBatch(c echo.Context) error {
	id := c.Param("id")
	tx := GetDB(c).Begin()
	if err := tx.Model(&domain.Voucher{}).Where("batch_id = ?", id).Update("is_deleted", true).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "DELETE_VOUCHERS_FAILED", "Failed to delete vouchers", err.Error())
	}
	if err := tx.Model(&domain.VoucherBatch{}).Where("id = ?", id).Update("is_deleted", true).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "DELETE_BATCH_FAILED", "Failed to delete batch", err.Error())
	}
	tx.Commit()
	return ok(c, nil)
}

// RestoreVoucherBatch restores a soft-deleted batch
func RestoreVoucherBatch(c echo.Context) error {
	id := c.Param("id")
	tx := GetDB(c).Begin()
	if err := tx.Model(&domain.Voucher{}).Where("batch_id = ?", id).Update("is_deleted", false).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "RESTORE_VOUCHERS_FAILED", "Failed to restore vouchers", err.Error())
	}
	if err := tx.Model(&domain.VoucherBatch{}).Where("id = ?", id).Update("is_deleted", false).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "RESTORE_BATCH_FAILED", "Failed to restore batch", err.Error())
	}
	tx.Commit()
	return ok(c, nil)
}

// RefundUnusedVouchers refunds unused vouchers to agent wallet
func RefundUnusedVouchers(c echo.Context) error {
	id := c.Param("id")
	db := GetDB(c)
	zap.L().Info("Refund attempt", zap.String("batch_id", id))

	var batch domain.VoucherBatch
	if err := db.First(&batch, id).Error; err != nil {
		zap.L().Error("Refund failed: batch not found", zap.String("batch_id", id), zap.Error(err))
		return fail(c, http.StatusNotFound, "BATCH_NOT_FOUND", "Batch not found", err.Error())
	}

	if batch.AgentID <= 0 {
		zap.L().Warn("Refund failed: no agent linked", zap.String("batch_id", id), zap.Int64("agent_id", batch.AgentID))
		return fail(c, http.StatusBadRequest, "NO_AGENT", "This batch was not generated by an agent", nil)
	}

	tx := db.Begin()

	var vouchers []domain.Voucher
	if err := tx.Where("batch_id = ? AND status = ?", id, "unused").Find(&vouchers).Error; err != nil {
		zap.L().Error("Refund failed: voucher query error", zap.String("batch_id", id), zap.Error(err))
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "QUERY_FAILED", "Failed to find unused vouchers", err.Error())
	}

	if len(vouchers) == 0 {
		zap.L().Warn("Refund failed: no unused vouchers found", zap.String("batch_id", id))
		tx.Rollback()
		return fail(c, http.StatusBadRequest, "NO_UNUSED", "No unused vouchers to refund", nil)
	}

	var totalRefund float64
	// Fetch product to get the cost price (same logic as creation)
	var product domain.Product
	if err := tx.First(&product, batch.ProductID).Error; err != nil {
		zap.L().Error("Refund failed: product not found", zap.String("batch_id", id), zap.Int64("product_id", batch.ProductID), zap.Error(err))
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "PRODUCT_ERROR", "Associated product not found", err.Error())
	}

	unitCost := product.CostPrice
	if unitCost <= 0 && product.Price > 0 {
		unitCost = product.Price
	}

	totalRefund = unitCost * float64(len(vouchers))

	// 1. Mark vouchers as deleted/refunded
	if err := tx.Model(&domain.Voucher{}).Where("batch_id = ? AND status = ?", id, "unused").Updates(map[string]interface{}{
		"status":     "refunded",
		"is_deleted": true,
	}).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "UPDATE_FAILED", "Failed to update voucher status", err.Error())
	}

	// 2. Refund Wallet
	var wallet domain.AgentWallet
	if err := tx.Set("gorm:query_option", "FOR UPDATE").FirstOrCreate(&wallet, domain.AgentWallet{AgentID: batch.AgentID}).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "WALLET_ERROR", "Failed to lock wallet", err.Error())
	}

	newBalance := wallet.Balance + totalRefund
	if err := tx.Model(&domain.AgentWallet{}).Where("agent_id = ?", batch.AgentID).Update("balance", newBalance).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "REFUND_FAILED", "Failed to update wallet balance", err.Error())
	}

	// 3. Log Transaction
	log := domain.WalletLog{
		AgentID:     batch.AgentID,
		Type:        "refund",
		Amount:      totalRefund,
		Balance:     newBalance,
		ReferenceID: fmt.Sprintf("refund-%d", batch.ID),
		Remark:      fmt.Sprintf("refunded %d unused vouchers (unit cost: %.2f) from batch %s", len(vouchers), unitCost, batch.Name),
		CreatedAt:   time.Now(),
	}
	if err := tx.Create(&log).Error; err != nil {
		tx.Rollback()
		return fail(c, http.StatusInternalServerError, "LOG_FAILED", "Failed to create log", err.Error())
	}

	tx.Commit()
	return ok(c, map[string]interface{}{"refunded_count": len(vouchers), "refund_amount": totalRefund})
}

// ExportVoucherBatch exports batch vouchers to CSV
func ExportVoucherBatch(c echo.Context) error {
	id := c.Param("id")

	var batch domain.VoucherBatch
	if err := GetDB(c).First(&batch, id).Error; err != nil {
		return fail(c, http.StatusNotFound, "BATCH_NOT_FOUND", "Batch not found", err.Error())
	}

	var product domain.Product
	if err := GetDB(c).First(&product, batch.ProductID).Error; err != nil {
		return fail(c, http.StatusNotFound, "PRODUCT_NOT_FOUND", "Product not found", err.Error())
	}

	var vouchers []domain.Voucher
	if err := GetDB(c).Where("batch_id = ?", id).Find(&vouchers).Error; err != nil {
		return fail(c, http.StatusInternalServerError, "EXPORT_FAILED", "Failed to find vouchers", err.Error())
	}

	nowStr := time.Now().Format("02012006")
	filename := fmt.Sprintf("%s-%s-%d-%s.csv", batch.Name, product.Name, batch.Count, nowStr)
	// Sanitize filename to prevent header injection or invalid characters
	filename = strings.ReplaceAll(filename, " ", "_")

	c.Response().Header().Set(echo.HeaderContentDisposition, fmt.Sprintf("attachment; filename=%s", filename))
	c.Response().Header().Set(echo.HeaderContentType, "text/csv")
	c.Response().WriteHeader(http.StatusOK)

	writer := csv.NewWriter(c.Response())
	if err := writer.Write([]string{"ID", "Code", "Status", "Price", "ExpireTime"}); err != nil {
		zap.L().Error("Failed to write CSV header", zap.Error(err))
		return fail(c, http.StatusInternalServerError, "EXPORT_FAILED", "Failed to write CSV header", err.Error())
	}
	for _, v := range vouchers {
		row := []string{
			fmt.Sprintf("%d", v.ID),
			v.Code,
			v.Status,
			fmt.Sprintf("%.2f", v.Price),
			v.ExpireTime.Format("2006-01-02 15:04:05"),
		}
		if err := writer.Write(row); err != nil {
			zap.L().Error("Failed to write CSV row", zap.Int64("voucher_id", v.ID), zap.Error(err))
			return fail(c, http.StatusInternalServerError, "EXPORT_FAILED", "Failed to write CSV row", err.Error())
		}
	}
	writer.Flush()
	return nil
}

func registerVoucherRoutes() {
	webserver.ApiGET("/voucher-batches", ListVoucherBatches)
	webserver.ApiGET("/vouchers", ListVouchers)
	webserver.ApiPOST("/voucher-batches", CreateVoucherBatch)
	webserver.ApiPOST("/voucher-batches/:id/activate", BulkActivateVouchers)
	webserver.ApiPOST("/voucher-batches/:id/deactivate", BulkDeactivateVouchers)
	webserver.ApiDELETE("/voucher-batches/:id", DeleteVoucherBatch)
	webserver.ApiPOST("/voucher-batches/:id/restore", RestoreVoucherBatch)
	webserver.ApiPOST("/voucher-batches/:id/refund", RefundUnusedVouchers)
	webserver.ApiGET("/voucher-batches/:id/export", ExportVoucherBatch)
	webserver.ApiPOST("/vouchers/redeem", RedeemVoucher)
}
