version: "2"

run:
  timeout: 5m
  tests: false

issues:
  exclude-rules:
    - path: go/

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gosec

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    misspell:
      locale: US

    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1006"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"

    gosec:
      excludes:
        - G401
        - G501
