#!/bin/bash

echo "=== Profile Tenant Isolation Debugging Checklist ==="
echo ""
echo "✅ STEP 1: Verify Backend is Running"
echo "   Check if backend starts successfully"
echo "   Look for: 'Backend ready on port 1816'"
echo ""

echo "✅ STEP 2: Check Your JWT Token"
echo "   Open browser console (F12) and run:"
echo ""
echo "   const token = localStorage.getItem('token');"
echo "   const payload = JSON.parse(atob(token.split('.')[1]));"
echo "   console.log('Token payload:', payload);"
echo "   console.log('Your tenant_id:', payload.tenant_id);"
echo ""
echo "   ▶ Expected: tenant_id should be a number (like 2, 3, etc.)"
echo "   ▶ If tenant_id is missing or undefined, you need to RE-LOGIN"
echo ""

echo "✅ STEP 3: Clear Old Token and Login Fresh"
echo "   1. Click 'Logout' in the UI"
echo "   2. Or run: localStorage.clear();"
echo "   3. Refresh the page (F5)"
echo "   4. Login again as tenant admin"
echo "   5. Check token again (Step 2) - should now have tenant_id"
echo ""

echo "✅ STEP 4: Create a Test Profile"
echo "   1. Go to Profiles page"
echo "   2. Click 'Create Profile'"
echo "   3. Fill in details (name: 'Test Profile 1')"
echo "   4. Click 'Save'"
echo ""
echo "   ▶ Open Network tab (F12) before clicking save"
echo "   ▶ Look for POST /api/v1/radius-profiles"
echo "   ▶ Click on it and check the Response"
echo "   ▶ Verify the response shows: \"tenant_id\": YOUR_TENANT_ID"
echo ""

echo "✅ STEP 5: Check Profile List"
echo "   1. Refresh the Profiles page"
echo "   2. Open Network tab (F12)"
echo "   3. Look for GET /api/v1/radius-profiles"
echo "   4. Check the Response"
echo ""
echo "   ▶ Should see your profile in the data array"
echo "   ▶ Each profile should have your tenant_id"
echo ""

echo "✅ STEP 6: Check Backend Logs"
echo "   Run: tail -50 backend.log | grep -i 'profile\\|tenant'"
echo ""
echo "   ▶ Look for any errors"
echo "   ▶ Look for tenant_id values"
echo ""

echo "✅ STEP 7: Test Product Dropdown"
echo "   1. Go to Products page"
echo "   2. Click 'Create Product'"
echo "   3. Check the 'Radius Profile' dropdown"
echo ""
echo "   ▶ Should show your profiles now"
echo ""

echo "=== COMMON ISSUES ==="
echo ""
echo "❌ Issue: Profile created but not visible"
echo "   Cause: Created with old token (no tenant_id)"
echo "   Fix: Logout and login again, then create new profile"
echo ""
echo "❌ Issue: Dropdown shows no profiles"
echo "   Cause: Old profiles have wrong tenant_id"
echo "   Fix: Create new profiles after fresh login"
echo ""
echo "❌ Issue: 'missing tenant identification' error"
echo "   Cause: JWT middleware not running or token invalid"
echo "   Fix: Clear localStorage and login again"
echo ""

echo "=== VERIFICATION COMMANDS ==="
echo ""
echo "# Check what tenant_id your profiles have:"
echo "sqlite3 rundata/toughradius.db 'SELECT id, name, tenant_id FROM radius_profile ORDER BY id DESC LIMIT 5;'"
echo ""
echo "# Check your JWT token:"
echo "echo 'localStorage.getItem(\"token\")' | node -e 'const readline = require(\"readline\"); const token = readline.question(\"\"); const payload = JSON.parse(Buffer.from(token.split(\".\")[1], \"base64\").toString()); console.log(payload);'"
echo ""

echo "=== Still Not Working? ==="
echo ""
echo "1. Share the Network tab screenshots:"
echo "   - POST /api/v1/radius-profiles (create)"
echo "   - GET /api/v1/radius-profiles (list)"
echo ""
echo "2. Share backend logs:"
echo "   - tail -100 backend.log"
echo ""
echo "3. Share JWT token payload:"
echo "   - Run Step 2 command and share output"
echo ""
