package domain

import (
	"time"
)

// AgentHierarchy represents the hierarchical relationship between agents in a multi-level
// agent network. This enables master agents to have sub-agents, creating a tree-like
// structure for commission distribution and territory management.
//
// The hierarchy supports unlimited levels where each agent can have multiple sub-agents,
// but each sub-agent has only one parent. This creates a proper tree structure without
// cycles or multiple inheritance.
//
// Database table: agent_hierarchy
//
// Key relationships:
//   - AgentID references sys_opr.id (must be level='agent')
//   - ParentID references sys_opr.id (must be level='agent' or null for root agents)
//   - Level indicates depth in hierarchy (0 = root, 1 = direct sub-agent, etc.)
//
// Commission flow:
//   - Commissions flow upward from sub-agents to parent agents
//   - Each level can have different commission rates
//   - Root agents receive commissions from all levels below them
//
// Territory management:
//   - Agents can be assigned geographic territories
//   - Sub-agents inherit territory restrictions from parents
//   - Territory assignments prevent conflicts between sibling agents
//
// Lifecycle:
//   1. Created when an agent is assigned to a parent agent
//   2. Updated when commission rates or territories change
//   3. Soft-deleted when agent relationship is terminated
//
// Concurrency: Safe for concurrent reads. Updates should use transactions.
type AgentHierarchy struct {
	// AgentID is the ID of the agent in this hierarchy position.
	// References sys_opr.id where level='agent'.
	// Primary key component, cannot be changed once set.
	AgentID int64 `json:"agent_id,string" gorm:"primaryKey;autoIncrement:false"`

	// ParentID is the ID of the parent agent in the hierarchy.
	// References sys_opr.id where level='agent', or null for root agents.
	// Null value indicates this agent is at the top level (master agent).
	ParentID *int64 `json:"parent_id,string" gorm:"index"`

	// Level indicates the depth in the hierarchy tree.
	// 0 = root agent (no parent), 1 = direct sub-agent, 2 = grandchild, etc.
	// Automatically calculated based on parent relationships.
	Level int `json:"level" gorm:"index"`

	// Territory defines the geographic region this agent is responsible for.
	// Used for market segmentation and preventing territory conflicts.
	// Format: Free text (e.g., "North Region", "City Center", "District A").
	Territory string `json:"territory" gorm:"size:255"`

	// CommissionRate is the percentage (0.0-1.0) this agent earns on sub-agent sales.
	// For example: 0.05 = 5% commission on all sales by direct sub-agents.
	// This rate applies to the agent's direct sub-agents, not to the entire tree.
	CommissionRate float64 `json:"commission_rate" gorm:"type:decimal(5,4);default:0.0000"`

	// Status indicates the current state of this agent relationship.
	// Possible values: "active", "inactive", "suspended", "terminated"
	// Only "active" agents participate in commission calculations.
	Status string `json:"status" gorm:"size:20;default:'active'"`

	// CreatedAt is automatically set when the hierarchy relationship is created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is automatically updated when the hierarchy is modified.
	UpdatedAt time.Time `json:"updated_at"`
}

// TableName specifies the database table name for AgentHierarchy
func (AgentHierarchy) TableName() string {
	return "agent_hierarchy"
}

// CommissionLog represents an immutable record of commission earnings and payments.
// Each log entry tracks a specific commission earned by an agent from a sub-agent's
// voucher sale or other revenue-generating activity.
//
// Commissions are calculated in real-time when transactions occur and logged
// immediately. This ensures auditability and prevents disputes about commission
// calculations.
//
// Database table: commission_log
//
// Commission types:
//   - direct_sale: Commission from agent's own voucher sales
//   - referral: Commission from sub-agent's voucher sales
//   - override: Commission from grandchild+ level sales (multi-level)
//
// Payment lifecycle:
//   1. Commission earned and logged with status="pending"
//   2. Periodically aggregated and marked "payable"
//   3. Paid out and marked "paid"
//   4. Can be "cancelled" if transaction is refunded
//
// Concurrency: Records are immutable once created. Use transactions for bulk operations.
type CommissionLog struct {
	// ID is the auto-incrementing primary key.
	// Generated by database on INSERT, immutable.
	ID int64 `json:"id,string" gorm:"primaryKey"`

	// AgentID is the ID of the agent earning this commission.
	// References sys_opr.id where level='agent'.
	AgentID int64 `json:"agent_id,string" gorm:"index"`

	// SourceAgentID is the ID of the agent whose sale generated this commission.
	// For direct_sale: same as AgentID
	// For referral/override: ID of the sub-agent who made the sale
	SourceAgentID int64 `json:"source_agent_id,string" gorm:"index"`

	// VoucherID is the ID of the voucher that generated this commission.
	// References voucher.id. Null for non-voucher related commissions.
	VoucherID *int64 `json:"voucher_id,string" gorm:"index"`

	// Amount is the commission amount earned.
	// Always positive. Currency matches system default (typically USD or local currency).
	Amount float64 `json:"amount" gorm:"type:decimal(10,2)"`

	// Type indicates how this commission was earned.
	// Values: "direct_sale", "referral", "override", "bonus"
	Type string `json:"type" gorm:"size:20;index"`

	// Level indicates the hierarchy level where this commission was earned.
	// 0 = direct sale (agent's own sale)
	// 1 = referral (direct sub-agent sale)
	// 2+ = override (grandchild+ level sales)
	Level int `json:"level" gorm:"index"`

	// Status tracks the payment lifecycle of this commission.
	// Values: "pending", "payable", "paid", "cancelled"
	// Only "paid" commissions are considered earned income.
	Status string `json:"status" gorm:"size:20;index;default:'pending'"`

	// PaidAt is set when status becomes "paid".
	// Null for unpaid commissions.
	PaidAt *time.Time `json:"paid_at"`

	// ReferenceID links this commission to the original transaction.
	// For vouchers: voucher.id as string
	// For other transactions: payment reference or transaction ID
	ReferenceID string `json:"reference_id" gorm:"size:100;index"`

	// Remark provides additional context about this commission.
	// Examples: "5% referral from agent XYZ voucher sale", "Override commission level 2"
	Remark string `json:"remark" gorm:"size:255"`

	// CreatedAt is set when the commission is earned (immutable).
	CreatedAt time.Time `json:"created_at" gorm:"index"`
}

// TableName specifies the database table name for CommissionLog
func (CommissionLog) TableName() string {
	return "commission_log"
}

// CommissionSummary provides aggregated commission data for reporting and analytics.
// This is a computed view/table that aggregates commission_log data for performance.
//
// Database table: commission_summary (materialized view or computed table)
//
// Update frequency: Should be refreshed daily or in real-time depending on requirements.
// Used for: Dashboard displays, agent statements, payout calculations.
type CommissionSummary struct {
	// AgentID is the agent whose commission summary this represents.
	AgentID int64 `json:"agent_id,string" gorm:"primaryKey"`

	// Period represents the time period for this summary.
	// Format: "2024-01" for monthly, "2024-W01" for weekly, "2024" for yearly
	Period string `json:"period" gorm:"primaryKey;size:10"`

	// TotalEarned is the sum of all commission amounts for this period.
	TotalEarned float64 `json:"total_earned" gorm:"type:decimal(12,2)"`

	// TotalPaid is the sum of paid commission amounts for this period.
	TotalPaid float64 `json:"total_paid" gorm:"type:decimal(12,2)"`

	// PendingAmount is TotalEarned - TotalPaid.
	PendingAmount float64 `json:"pending_amount" gorm:"type:decimal(12,2)"`

	// DirectSales are commissions from the agent's own sales.
	DirectSales float64 `json:"direct_sales" gorm:"type:decimal(12,2)"`

	// ReferralSales are commissions from direct sub-agent sales.
	ReferralSales float64 `json:"referral_sales" gorm:"type:decimal(12,2)"`

	// OverrideSales are commissions from grandchild+ level sales.
	OverrideSales float64 `json:"override_sales" gorm:"type:decimal(12,2)"`

	// TransactionCount is the number of commission transactions in this period.
	TransactionCount int64 `json:"transaction_count"`

	// LastUpdated indicates when this summary was last refreshed.
	LastUpdated time.Time `json:"last_updated"`
}

// TableName specifies the database table name for CommissionSummary
func (CommissionSummary) TableName() string {
	return "commission_summary"
}

// PayoutRequest represents a payout request from an agent to withdraw their commission earnings.
// This initiates the payout process which requires admin approval before funds are transferred.
//
// Database table: payout_request
//
// Lifecycle:
//   1. Created by agent via API (status: "pending")
//   2. Reviewed by admin (status: "approved" or "rejected")
//   3. If approved, PayoutLog created and wallet balance updated (status: "completed")
//   4. If rejected, request remains with rejection reason
//
// Security: Only the requesting agent or admins can view the request details.
// Admins can approve/reject any payout request.
type PayoutRequest struct {
	// ID is the auto-incrementing primary key.
	ID int64 `json:"id,string" gorm:"primaryKey"`

	// AgentID is the agent requesting the payout.
	AgentID int64 `json:"agent_id,string" gorm:"index"`

	// Amount is the requested payout amount.
	// Must be <= current wallet balance.
	Amount float64 `json:"amount" gorm:"type:decimal(10,2)"`

	// PaymentMethod specifies how the agent wants to receive payment.
	// Values: "bank_transfer", "paypal", "crypto", "cash", "check"
	PaymentMethod string `json:"payment_method" gorm:"size:20"`

	// PaymentDetails contains payment-specific information.
	// For bank_transfer: JSON with account details
	// For paypal: email address
	// For crypto: wallet address
	PaymentDetails string `json:"payment_details" gorm:"type:text"`

	// Status tracks the payout request lifecycle.
	// Values: "pending", "approved", "rejected", "completed", "cancelled"
	Status string `json:"status" gorm:"size:20;index;default:'pending'"`

	// Notes contains additional information from the agent.
	Notes string `json:"notes" gorm:"size:500"`

	// AdminNotes contains review comments from the admin.
	AdminNotes string `json:"admin_notes" gorm:"size:500"`

	// ReviewedBy is the admin who reviewed this request (if any).
	ReviewedBy *int64 `json:"reviewed_by,string"`

	// ReviewedAt is when the request was reviewed.
	ReviewedAt *time.Time `json:"reviewed_at"`

	// CreatedAt is when the request was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is when the request was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// TableName specifies the database table name for PayoutRequest
func (PayoutRequest) TableName() string {
	return "payout_request"
}

// PayoutLog represents a completed payout transaction.
// This is created when a payout request is approved and funds are transferred.
//
// Database table: payout_log
//
// Purpose: Immutable audit trail of all payout transactions.
// Used for: Financial reporting, agent statements, tax records.
type PayoutLog struct {
	// ID is the auto-incrementing primary key.
	ID int64 `json:"id,string" gorm:"primaryKey"`

	// AgentID is the agent who received the payout.
	AgentID int64 `json:"agent_id,string" gorm:"index"`

	// PayoutRequestID links to the original payout request.
	PayoutRequestID int64 `json:"payout_request_id,string" gorm:"index"`

	// Amount is the actual payout amount (may differ from request if partial).
	Amount float64 `json:"amount" gorm:"type:decimal(10,2)"`

	// PaymentMethod used for this payout.
	PaymentMethod string `json:"payment_method" gorm:"size:20"`

	// PaymentDetails used for this payout.
	PaymentDetails string `json:"payment_details" gorm:"type:text"`

	// TransactionID is the external payment system reference (if applicable).
	// For bank transfers: reference number
	// For paypal: transaction ID
	TransactionID string `json:"transaction_id" gorm:"size:100"`

	// ProcessedBy is the admin who processed this payout.
	ProcessedBy int64 `json:"processed_by,string"`

	// ProcessedAt is when the payout was completed.
	ProcessedAt time.Time `json:"processed_at"`

	// Notes contains any additional information about the payout.
	Notes string `json:"notes" gorm:"size:500"`
}

// TableName specifies the database table name for PayoutLog
func (PayoutLog) TableName() string {
	return "payout_log"
}
