// Package domain defines data models for ToughRADIUS.
//
// This file adds the Invoice model for postpaid monthly billing.
// An Invoice tracks a single billing cycle charge for a postpaid subscriber.
// Invoices are generated automatically by the billing engine cron job at the
// start of each subscriber's billing cycle (rolling 30-day by default).
//
// Lifecycle:
//  1. Generated by billing engine when user's NextBillingDate is reached.
//  2. Status starts as "unpaid".
//  3. Admin marks as "paid" via API after cash/payment collection.
//  4. If unpaid past DueDate, status transitions to "overdue" and user is suspended.
//
// Database table: invoice
package domain

import (
	"time"
)

// Billing type constants control how a RadiusUser is billed.
//   - BillingTypePrepaid: Traditional voucher/card-based access with fixed expiry.
//   - BillingTypePostpaid: Monthly subscription billed at end of cycle.
const (
	BillingTypePrepaid  = "prepaid"
	BillingTypePostpaid = "postpaid"
)

// Subscription status constants describe the state of a postpaid user's subscription.
//   - SubscriptionActive: User has an active subscription and can authenticate.
//   - SubscriptionSuspended: User has unpaid invoice(s) past due date; auth is rejected.
//   - SubscriptionCanceled: Subscription permanently ended by admin.
const (
	SubscriptionActive    = "active"
	SubscriptionSuspended = "suspended"
	SubscriptionCanceled  = "canceled"
)

// Invoice status constants describe the payment state of a generated invoice.
//   - InvoiceUnpaid: Invoice generated, awaiting payment.
//   - InvoicePaid: Payment collected, recorded by admin.
//   - InvoiceOverdue: DueDate has passed without payment; triggers user suspension.
const (
	InvoiceUnpaid  = "unpaid"
	InvoicePaid    = "paid"
	InvoiceOverdue = "overdue"
)

// Invoice categories
const (
	InvoiceCategoryService = "service"
	InvoiceCategoryTopup   = "topup"
)

// Invoice represents a single monthly billing record for a postpaid subscriber.
//
// Each invoice covers a specific billing period (BillingPeriodStart to BillingPeriodEnd)
// and tracks the amount charged based on the user's assigned RadiusProfile.
// The billing engine generates invoices when a user's NextBillingDate is reached
// and updates the user's NextBillingDate to the next cycle start.
//
// The DueDate is typically 7 days after IssueDate (configurable via billing settings).
// If an invoice remains unpaid past DueDate, the EnforceOverdueSuspensions job
// transitions its status to "overdue" and suspends the user's subscription.
//
// Database table: invoice
// GORM features: Auto-migration, timestamps, indexed on username and status.
//
// Concurrency: Safe for concurrent read. Write operations should use GORM transactions
// when updating both Invoice and RadiusUser state together.
type Invoice struct {
	ID                int64     `json:"id,string" form:"id" gorm:"primaryKey"`
	Username          string    `json:"username" gorm:"index;not null;size:255"` // Links to RadiusUser.Username
	ProfileID         int64     `json:"profile_id,string"`                       // The profile charged for this cycle
	Amount            float64   `json:"amount"`                                  // Total charge amount
	BaseAmount        float64   `json:"base_amount"`                             // Monthly base fee
	UsageGb           float64   `json:"usage_gb"`                                // Data usage in GB
	PricePerGb        float64   `json:"price_per_gb"`                            // Rate per GB
	SessionCount      int64     `json:"session_count"`                           // Number of accounting sessions
	Currency          string    `json:"currency" gorm:"size:10;default:'USD'"`   // Currency code
	IssueDate         time.Time `json:"issue_date" gorm:"index"`                 // Date the invoice was generated
	DueDate           time.Time `json:"due_date" gorm:"index"`                   // Payment deadline
	PaidAt            time.Time `json:"paid_at"`                                 // Timestamp when paid
	Status            string    `json:"status" gorm:"index;size:20;default:'unpaid'"`
	BillingPeriodStart time.Time `json:"billing_period_start"`
	BillingPeriodEnd   time.Time `json:"billing_period_end"`
	Remark            string    `json:"remark" gorm:"size:500"`
	Category          string    `json:"category" gorm:"index;size:50;default:'service'"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// TableName specifies the database table name for GORM auto-migration.
func (Invoice) TableName() string {
	return "invoice"
}
